### ISSUE TITLE
Não valida o que é digitado

### ISSUE THREAD

**Issue by gustavoJunkes** [EduardoZirbell/JogoDeCartas#1]
O sistema não informa para o usuário a carta e o naipe sorteado, assim não é possível validar se a forma em que informei as cartas está correta. 

Exemplo: 
`Informe o naipe da carta que você acha que é: ouros `
O sistema retorna:
`A carta sorteada tem naipe diferente do seu chute! `

Nesse caso, não há como saber se o input é valido.

**Comment by EduardoZirbell** [comment]
Faz tempo ein Gustavo. Valeu pela dica, vou arrumar e já posto aqui!
